name: Docker agent workflow

on: 
  workflow_dispatch:
  # push:
  #   branches: ['master']

jobs:
  build:
    runs-on: [ubuntu-latest]

    container:
      image: node:16-alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install || echo "No package.json found, skipping install"

      - name: check version
        run: node --version
